#!/bin/bash

if (( UID != 0)); then
    echo "Merci d'utiliser ce script en tant que superuser"
    exit 1
fi

VM=$1
LEN=${#VM}
date=$(date '+%Y-%m-%d')
if ((LEN == 0)); then
	VM=$(virsh list --all | awk '{print $2}' | grep '\S' | tail -n +2)
	for name in ${VM[@]}; do

	STATE=$(virsh dominfo "$name" | grep State | awk '{print $2}')
	MACADDR=$(virsh domiflist "$name" | awk '{print $5}' | grep '\S' | tail -n +2)
	IP=$(arp -n | grep  "${MACADDR}"| awk '{print $1}')
	printf "Nom de la machine : "$name"\nStatus : ${STATE}\nMAC ADDRESS :\n${MACADDR}\nIP:\n${IP}\n" >> /home/miko/os/gestion/$name-$date.txt
	done

fi
